import { Inter } from 'next/font/google'
import './globals.css'
import Hedaer from './component/Hedaer'
import { ThemeProvider } from 'next-themes'
import Providers from './providers'
import NavBar from './component/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Imbd-Next',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Hedaer />
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
